[build]
  builder = "NIXPACKS"
  buildCommand = "npm install --include=dev && npm run build && npm prune --production"

[deploy]
  startCommand = "npm start"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 3
